### PR TITLE
update only changed fields; serialize values for rails3

### PR DESCRIPTION
**Pull request by ritikesh**
referenced from - #11

### CODE REVIEW

**Comment by einzige** [comment]
cool, thanks man, I will knock this out this week

**Comment by ritikesh** [comment]
Thank you!

**Comment by einzige** [comment]
@ritikesh  https://github.com/einzige/sneaky-save/pull/13/commits/4722f588b3c45a4202c0488cdd77d096919aeafc

**Comment by einzige** [comment]
@ritikesh hey man, this one is for you (since it was your call 😸 ): https://github.com/einzige/sneaky-save/pull/14

The only thing missing there is a spec.

**Comment by ritikesh** [comment]
Hey, great news! And thanks a lot for being patient with me! 😄

**Pull request closed without merging**
