### PR TITLE
Update version from file and bumping version

### PR DESCRIPTION
**Pull request by ritikesh**

### CODE REVIEW

**Comment by ritikesh** [comment]
@einzige can we release this version? Thanks!

**Comment by einzige** [comment]
will do

**Comment by ritikesh** [comment]
@einzige has it been released? can't find it on [rubygems](https://rubygems.org/gems/sneaky-save)

**Comment by einzige** [comment]
@ritikesh https://rubygems.org/gems/sneaky-save/versions/0.1.3

**Comment by ritikesh** [comment]
awesome, thanks! 👍

**Comment by einzige** [comment]
I only fucked up with setting release date :( It now says 2016 😆

**Comment by ritikesh** [comment]
Noticed! 🤣

**Pull request merged**
