### PR TITLE
Fix Rails 3 serialized attributes

### PR DESCRIPTION
**Pull request by einzige**
- [x] Add spec

@ritikesh 

Going forward, let's have our updates separated in commits.

For a spec, you'll need to update `spec/spe_helper.rb` where you'll find a test class called "Fake", just add a new column to it and serialize the way you did in your app. 

It may also require you to add conditional spec / code depending on a currently running rails/AR version, eg: `if ActiveRecord.version < 4 then add serialization, run this spec`

### CODE REVIEW

**Comment by ritikesh** [comment]
> It may also require you to add conditional spec / code depending on a currently running rails/AR version, eg: if ActiveRecord.version < 4 then add serialization, run this spec
Doubt that it would require version checks. Serialized columns should work irrespective of whichever version we're on right? 
Let me know your thoughts. Thanks.

**Comment by einzige** [comment]
@ritikesh yep, sounds right

**Comment by ritikesh** [comment]
@einzige when I ran specs, it ran with 0 failures. How about you?

**Comment by einzige** [comment]
@ritikesh right, but we need to make sure a serialized column gets saved. For instance:

```ruby
it 'updates serialized column' do
  expect do
     fake.config = {one: :two}
     fake.sneaky_save!
  end.to change { fake.reload.config }.from(nil).to(one: :two)
end

```

**Pull request merged**
