### PR TITLE
Add unscope when sneaky_update

### PR DESCRIPTION
**Pull request by aditiamahdar**

### CODE REVIEW

**Comment by ritikesh** [comment]
What's your use-case for doing this?

**Comment by aditiamahdar** [comment]
@ritikesh I am having issue when trying to update column with default scope.

e.g: I have `user` record with column `deleted_at`, that column is default scope, if the column is nil then show the record, if not nil then app assume it's deleted.
Then I have function to restore that deleted record, when I use `sneaky_save!` it return false because it cannot find the record, it's looking for the id and still using the default scope.

**Comment by einzige** [comment]
@aditiamahdar thank you!

**Comment by aditiamahdar** [comment]
@einzige you are welcome

**Pull request merged**
